FROM node:11-stretch

# Since npm will install all dependencies in the local directory you don't need to run
# npm install with your package.json. Just install your dev dependencies here.
RUN npm install --unsafe-perm -g eslint
